Feature/#6 as a personal user i should be able to send connect requests to use
2055Java-Nick/Rev-Connect-UI pull request #33
Opened 2024-08-26 21:35 UTC by Nate-Lema

2024-08-27 13:32 UTC, asif-kamal approved these changes

2024-08-28 17:48 UTC, themellowpea requested changes
See comments -- requires some refactoring. Good start

2024-08-28 17:48 UTC, themellowpea commented on src/assets/user.jpg
Can we use a smaller file size format like png? or SVG?

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/Dashboard.tsx
> +      <main className="main-content">
We don't have to use semantic tags. There may be another `<main>` element on the page at the same time.

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/Dashboard.tsx
> +          handleRemoveConnection={handleRemoveConnection}
I would replace all these props and create hooks that handle all the logic, then call the hooks within the components. This way we can mock the hooks or use the actual hooks and not worry about props in our components

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/Dashboard.tsx
> +          <a href="/contact">Contact Us</a>
Use `<Link />` tags here so that we save the browser memory. They are a apart of `react-router-dom` components.

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/Header.tsx
> +      <a href="/messages">Messages</a>
Use `<Link />` here as well

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/MyConnections.tsx
> +export interface MyConnectionsProps {
Create a types file for these definitions so we can export/import them from an appropriate place, ie the `/types` dir.

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/PendingRequests.tsx
> +export interface PendingRequestsProps {
use a types file for these definitions

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/SearchBar.tsx
> +export interface SearchBarProps {
use a types file for these definitions

2024-08-28 17:48 UTC, themellowpea commented on src/components/ConnectionPage/SearchBar.tsx
> +              </button>
Nesting ternary logic isn't preferred. maybe extract this to it's own component or 
``` typescript
function searchResults() {
    return searchResults.map(user => {
        if (user.isSameUser) return < your jsx >;
        if (user.hadPendingRequest) return </>;
        return < default jsx />;
    )}
}
...

<ul className="search-results">
{searchResults}
</ul>
```

2024-08-28 17:48 UTC, themellowpea commented on src/routes/index.tsx
> +  },
Move this to the first element of this array, in its `children` array.

2024-08-28 17:48 UTC, themellowpea commented on src/services/api.ts
> +//connection api
You want to create a separate services file, ie connectionService.ts and put all this logic in there. Use the apiClient object exported from this file to get the basic configuration for the axios client.

2024-08-28 17:48 UTC, themellowpea commented on src/styles/pages/ConnectionPage.css
> +body, html {
Let's use bootstrap for styling. Try and replace the styling with bootstrap styling and make is basic as possible for our mvp

2024-08-28 17:48 UTC, themellowpea commented on src/styles/pages/Toastify.css
> +.custom-toast {
Use bootstrap

2024-09-03 17:16 UTC, closed without merging