#3 - added-tsx-registration-form
2055Java-Nick/Rev-Connect-UI pull request #7
Opened 2024-08-14 15:54 UTC by asif-kamal

2024-08-14 18:59 UTC, themellowpea requested changes
Can you remove the package.json and package-lock.json files? I don't think we are using webpack for this project

2024-08-14 19:12 UTC, asif-kamal commented
> Can you remove the package.json and package-lock.json files? I don't think we are using webpack for this project
Made the changes. Was unsure whether I should re-commit and push the new changes or have this PR re-reviewed.

2024-08-14 19:43 UTC, themellowpea commented on src/ApplicationForm.tsx
> +<<<<<<< Updated upstream
remove please :)

2024-08-15 15:41 UTC, themellowpea approved these changes

2024-08-15 20:40 UTC, anji-annavarapu approved these changes

2024-08-15 20:41 UTC, anji-annavarapu approved these changes

2024-08-15 20:42 UTC, anji-annavarapu approved these changes

2024-09-03 17:17 UTC, closed without merging